# Generated by Django 4.1.6 on 2023-02-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=1, upload_to='users/profile'),
            preserve_default=False,
        ),
    ]
